### ISSUE TITLE
Should I have keywords in package.json

### ISSUE THREAD

**Issue by sotayamashita** [morishitter/psg-theme-default#1]
When I create a theme, should I have keywords like `psg-theme` in `package.json` such as [PostCSS Plugin Guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#44-postcss-plugin-keyword-in-packagejson) ?

**Comment by msaktype** [comment]
Yep, I just updated the [guideline](https://github.com/morishitter/postcss-style-guide/blob/master/docs/theme-guideline.md).
